version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate proto files"
    cmds:
      - protoc -I proto proto/*/*.proto -I ./third_party/googleapis 
        --go_out=./gen/go/ --go_opt=paths=source_relative 
        --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
        --grpc-gateway_out=./gen/go/ --grpc-gateway_opt=paths=source_relative,generate_unbound_methods=true
